language: julia
julia:
  - nightly
  - 0.7

script:
  - julia -e "using Pkg;Pkg.clone(pwd()); Pkg.build(\"ANOVA\")"
#  - julia test/runtest.jl


after_success:
  - julia -e 'using Pkg;Pkg.add("Documenter")'
  - julia -e 'using Pkg;cd(Pkg.dir("ANOVA")); include(joinpath("docs", "make.jl"))'
