language: julia
julia:
  - nightly
  - 0.6

script:
  - julia -e "Pkg.clone(pwd()); Pkg.build(\"ANOVA\")"
#  - julia test/runtest.jl


after_success:
  - julia -e 'Pkg.add("Documenter")'
  - pip install mkdocs-material
  - julia -e 'cd(Pkg.dir("ANOVA")); include(joinpath("docs", "make.jl"))'
