language: julia
julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

script:
  - julia -e "using Pkg;Pkg.clone(pwd()); Pkg.build(\"ANOVA\")"
#  - julia test/runtest.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia -e "using Pkg; Pkg.add(\"Documenter\")"
        - julia docs/make.jl
      after_success: skip
